[profile.default]
evm_version = "cancun"
gas_reports = ["*"]
gas_reports_ignore = []
ignored_error_codes = []
optimizer = true
optimizer_runs = 999999
solc_version = "0.8.26"
verbosity = 3
# Used to deploy transparent proxies
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
no_match_coverage = "script|test"
ignored_warnings_from = ["lib", "test", "script"]
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read-write", path = "./out" },
]

[lint]
lint_on_build = false

[profile.production]
build_info = true
sizes = true

[fuzz]
runs = 5_000

[invariant]
runs = 512            # The number of calls to make in the invariant tests
depth = 25            # The number of times to run the invariant tests
fail_on_revert = true # Fail the test if the contract reverts

[profile.ci.fuzz]
runs = 10_000

[profile.ci.invariant]
runs = 512
depth = 250

[rpc_endpoints]
localhost = "${LOCALHOST_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=1" }
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=42161" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainid=11155111" }

# See more config options at https://github.com/foundry-rs/foundry/tree/master/crates/config
